enum error_ids {
  OK = 0,
  CPU_NOT_SUPPORTED,
  NO_VALID_DIRECTIVE_OR_MNEMONIC,
  NOT_A_VALID_NUMBER,
  NOT_AN_OPERATOR,
  PARANTHESIS_MISSMATCH,
  SYMBOL_NOT_FOUND,
  SYMBOL_ALREADY_EXIST,
  
  ASM_ADDR_IMMEDIATE_TO_BIG,
  ASM_UNEXPECTED_CHARACTER,
  ASM_INVALID_ADDRESSING_MODE,
  ASM_INDIRECT_MODE_INVALID,
};

extern unsigned char *error_msgs[];

